-- GENERATED by mission_toolkit (Voidwatch > Atmacite warp checklist). Do not hand-edit; edit in the toolkit and re-export.
-- Entries missing an option id, zone id or coordinate are comments only and never warp.
-- Option = (destId * 65536) + 2 as sent by the client in onEventFinish [C-log]; era: present / past ([S]).
VWO_WARPS = {
    -- present Indigo Bastok 1: North_Gustaberg (outside Port Bastok)
    [458754] = {era = "present", stone = "Indigo", tier = 1, zone = 106, x = 660.0, y = -2.478, z = 306.236, rot = 64},
    -- present Indigo Bastok 2: Gusgen_Mines (immediately outside the Gusgen Mines entrance in Konschtat_Highlands)
    [589826] = {era = "present", stone = "Indigo", tier = 2, zone = 108, x = 684.32, y = 22.58, z = 204.1, rot = 225},
    -- present Indigo Bastok 3: Pashhow_Marshlands (near the Konschtat Highlands entrance)
    [655362] = {era = "present", stone = "Indigo", tier = 3, zone = 109, x = -542.83, y = 25.0, z = -645.38, rot = 202},
    -- present Indigo Bastok 4: Dangruf_Wadi (immediately outside the Dangruf Wadi entrance in South_Gustaberg)
    [786434] = {era = "present", stone = "Indigo", tier = 4, zone = 107, x = -600.0, y = 40.0, z = -520.0, rot = 128},
    -- present Crimson San d'Oria 1: East_Ronfaure (outside Southern San d'Oria)
    [65538] = {era = "present", stone = "Crimson", tier = 1, zone = 101, x = 86.131, y = -65.817, z = 273.861, rot = 30},
    -- present Crimson San d'Oria 2: Ordelles_Caves (entrance (outdoor landing zone not given by wiki))
    [196610] = {era = "present", stone = "Crimson", tier = 2, zone = 193, x = -83.0, y = 0.5, z = 660.0, rot = 128},
    -- present Crimson San d'Oria 3: Jugner_Forest (Jugner Forest)
    [262146] = {era = "present", stone = "Crimson", tier = 3, zone = 104, x = -574.33, y = -3.0, z = -441.59, rot = 0},
    -- present Crimson San d'Oria 4: King_Ranperres_Tomb (King Ranperre's Tomb (Entrance))
    [393218] = {era = "present", stone = "Crimson", tier = 4, zone = 190, x = -130.35, y = 0.0, z = 256.16, rot = 65},
    -- present Jade Windurst 1: West_Sarutabaruta (outside Windurst Waters)
    [851970] = {era = "present", stone = "Jade", tier = 1, zone = 115, x = 320.75, y = -5.12, z = -22.05, rot = 65},
    -- present Jade Windurst 2: Maze_of_Shakhrami (entrance (outdoor landing zone not given by wiki))
    [983042] = {era = "present", stone = "Jade", tier = 2, zone = 118, x = -325.02, y = -40.85, z = 285.5, rot = 173},
    -- present Jade Windurst 3: Meriphataud_Mountains
    [1048578] = {era = "present", stone = "Jade", tier = 3, zone = 119, x = -122.75, y = -24.0, z = -598.0, rot = 157},
    -- present Jade Windurst 4: Outer_Horutoto_Ruins (entrance (outdoor landing zone not given by wiki))
    [1179650] = {era = "present", stone = "Jade", tier = 4, zone = 116, x = 259.76, y = -17.24, z = -437.88, rot = 65},
    -- present White Jeuno 1: Batallia_Downs -- SKIPPED: incomplete
    -- present White Jeuno 1: Rolanberry_Fields -- SKIPPED: incomplete
    -- present White Jeuno 1: Sauromugue_Champaign -- SKIPPED: incomplete
    -- present White Jeuno 2: The_Eldieme_Necropolis (entrance) -- SKIPPED: incomplete
    -- present White Jeuno 2: Garlaige_Citadel (upper cliff entrance near the Sauromugue Cavernous Maw) -- SKIPPED: incomplete
    -- present White Jeuno 2: Crawlers_Nest (upper cliff entrance near Drooling Daisy spawn area) -- SKIPPED: incomplete
    -- present White Jeuno 3: Behemoths_Dominion -- SKIPPED: incomplete
    -- present White Jeuno 3: Qufim_Island -- SKIPPED: incomplete
    -- present White Jeuno 3: Lower_Delkfutt_Tower (immediately outside the entrance on Qufim Island) -- SKIPPED: incomplete
    -- present White Jeuno 4: East_Sarutabaruta (outside Windurst Woods) -- SKIPPED: incomplete
    -- present White Jeuno 4: South_Gustaberg (outside Bastok Mines) -- SKIPPED: incomplete
    -- present White Jeuno 4: West_Ronfaure (outside Northern San d'Oria) -- SKIPPED: incomplete
    -- present White Jeuno 5: Konschtat_Highlands (near North Gustaberg and the Abyssea-Konschtat maw) -- SKIPPED: incomplete
    -- present White Jeuno 5: La_Theine_Plateau (near West Ronfaure and the Abyssea-La Theine maw) -- SKIPPED: incomplete
    -- present White Jeuno 5: Tahrongi_Canyon (near East Sarutabaruta and the Abyssea-Tahrongi maw) -- SKIPPED: incomplete
    -- present White Jeuno 6: Beaucedine_Glacier (near Batallia Downs zone) -- SKIPPED: incomplete
    -- present White Jeuno 6: Valkurm_Dunes (outside Selbina) -- SKIPPED: incomplete
    -- present White Jeuno 6: Buburimu_Peninsula (outside Mhaura) -- SKIPPED: incomplete
    -- present Ashen Zilart 1: Yuhtunga_Jungle (outside Kazham) -- SKIPPED: incomplete
    -- present Ashen Zilart 1: Ifrits_Cauldron (entrance) -- SKIPPED: incomplete
    -- present Ashen Zilart 1: Temple_of_Uggalepih (entrance) -- SKIPPED: incomplete
    -- present Ashen Zilart 1: Western_Altepa_Desert (outside Rabao) -- SKIPPED: incomplete
    -- present Ashen Zilart 1: Quicksand_Caves (entrance; wiki: lands at (J-9) Western Altepa Desert among Antica) -- SKIPPED: incomplete
    -- present Ashen Zilart 1: Kuftal_Tunnel (entrance) -- SKIPPED: incomplete
    -- present Ashen Zilart 2: The_Sanctuary_of_ZiTah -- SKIPPED: incomplete
    -- present Ashen Zilart 2: The_Boyahda_Tree (entrance) -- SKIPPED: incomplete
    -- present Ashen Zilart 2: RoMaeve -- SKIPPED: incomplete
    -- present Ashen Zilart 3: Hall_of_the_Gods -- SKIPPED: incomplete
    -- present Hyacinth Tavnazia 1: Lufaise_Meadows (outside Tavnazian Safehold)
    [3670018] = {era = "present", stone = "Hyacinth", tier = 1, zone = 24, x = -589.56, y = -2.98, z = -97.56, rot = 122},
    -- present Hyacinth Tavnazia 1: Misareaux_Coast -- SKIPPED: incomplete
    -- present Hyacinth Tavnazia 1: Attohwa_Chasm (outside the Maze of Shakhrami) -- SKIPPED: not validated (untested)
    -- present Hyacinth Tavnazia 1: Uleguerand_Range (outside Xarcabard) -- SKIPPED: not validated (untested)
    -- present Hyacinth Tavnazia 2: Bibiki_Bay (Purgonorgo Isle) -- SKIPPED: incomplete
    -- present Amber Aht Urhgan 1: Caedarva_Mire (outside Nashmau) -- SKIPPED: incomplete
    -- present Amber Aht Urhgan 1: Mount_Zhayolm ((L-7)) -- SKIPPED: incomplete
    -- present Amber Aht Urhgan 1: Mamook (entrance) -- SKIPPED: incomplete
    -- present Amber Aht Urhgan 1: Arrapago_Reef (Arrapago Reef entrance, near the ??? used for Lamian Fang Keys) -- SKIPPED: incomplete
    -- present Amber Aht Urhgan 2: Aydeewa_Subterrane (entrance) -- SKIPPED: incomplete
    -- past Indigo Bastok 1: North_Gustaberg_[S] (outside Bastok Markets [S]) -- SKIPPED: incomplete
    -- past Indigo Bastok 3: Pashhow_Marshlands_[S] -- SKIPPED: incomplete
    -- past Crimson San d'Oria 1: East_Ronfaure_[S] (outside Southern San d'Oria [S]) -- SKIPPED: incomplete
    -- past Crimson San d'Oria 3: Jugner_Forest_[S] -- SKIPPED: incomplete
    -- past Jade Windurst 1: West_Sarutabaruta_[S] (outside Windurst Waters [S]) -- SKIPPED: incomplete
    -- past Jade Windurst 3: Meriphataud_Mountains_[S] -- SKIPPED: incomplete
    -- past White Jeuno 1: Batallia_Downs_[S] -- SKIPPED: incomplete
    -- past White Jeuno 1: Rolanberry_Fields_[S] -- SKIPPED: incomplete
    -- past White Jeuno 1: Sauromugue_Champaign_[S] -- SKIPPED: incomplete
    -- past White Jeuno 2: The_Eldieme_Necropolis_[S] (entrance) -- SKIPPED: incomplete
    -- past White Jeuno 2: Garlaige_Citadel_[S] (upper cliff entrance near Sauromugue [S] Cavernous Maw) -- SKIPPED: incomplete
    -- past White Jeuno 2: Crawlers_Nest_[S] (upper cliff entrance) -- SKIPPED: incomplete
    -- past White Jeuno 6: Grauberg_[S] -- SKIPPED: incomplete
    -- past White Jeuno 6: Fort_Karugo-Narugo_[S] -- SKIPPED: incomplete
    -- past White Jeuno 6: Vunkerl_Inlet_[S] -- SKIPPED: incomplete
};
