-- Converted from Topaz `mob_spawn_points` to DSP's real column order/shape.

INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092629, 'Archaic_Rampart', 'Archaic Rampart', 18000, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092631, 'Greatclaw', 'Greatclaw', 18001, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092637, 'Stygian_Pugil', 'Stygian Pugil', 18002, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092641, 'Kulshedra', 'Kulshedra', 18003, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092643, 'Bouncing_Ball', 'Bouncing Ball', 18004, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092646, 'Thousand_Eyes', 'Thousand Eyes', 18005, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092649, 'Mousse', 'Mousse', 18006, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092653, 'Black_Pudding', 'Black Pudding', 18007, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092655, 'Killing_Weapon', 'Killing Weapon', 18008, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092657, 'Ominous_Weapon', 'Ominous Weapon', 18009, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092659, 'Magic_Flagon', 'Magic Flagon', 18010, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092661, 'Friars_Lantern', 'Friar\'s Lantern', 18011, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092663, 'Sweeping_Cluster', 'Sweeping Cluster', 18012, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092665, 'Friars_Lantern', 'Friar\'s Lantern', 18011, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092667, 'Garm', 'Garm', 18013, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092670, 'Tainted_Flesh', 'Tainted Flesh', 18014, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092673, 'Draugar', 'Draugar', 18015, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092677, 'Bhoot', 'Bhoot', 18016, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092679, 'Carmine_Eruca', 'Carmine Eruca', 18017, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092682, 'Spinner', 'Spinner', 18018, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092685, 'Wamouracampa', 'Wamouracampa', 18019, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092689, 'Wamoura', 'Wamoura', 18020, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092691, 'Imp', 'Imp', 18021, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092700, 'Imp', 'Imp', 18021, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092701, 'Psycheflayer', 'Psycheflayer', 18022, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092702, 'Psycheflayer', 'Psycheflayer', 18022, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092703, 'Puk', 'Puk', 18023, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092713, 'Wyvern', 'Wyvern', 18024, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092715, 'Marsh_Murre', 'Marsh Murre', 18025, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092718, 'Lesser_Colibri', 'Lesser Colibri', 18026, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092721, 'Ziz', 'Ziz', 18027, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092725, 'Peryton', 'Peryton', 18028, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092727, 'Wild_Karakul', 'Wild Karakul', 18029, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092730, 'Wajaom_Tiger', 'Wajaom Tiger', 18030, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092733, 'Manticore', 'Manticore', 18031, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092737, 'Marid', 'Marid', 18032, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092739, 'Death_Cap', 'Death Cap', 18033, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092742, 'Puktrap', 'Puktrap', 18034, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092745, 'Leshy', 'Leshy', 18035, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092749, 'Ameretat', 'Ameretat', 18036, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092751, 'Sand_Lizard', 'Sand Lizard', 18037, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092754, 'Deinonychus', 'Deinonychus', 18038, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092757, 'Bull_Bugard', 'Bull Bugard', 18039, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092761, 'Wivre', 'Wivre', 18040, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092763, 'Bouncing_Ball', 'Bouncing Ball', 18004, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092768, 'Thousand_Eyes', 'Thousand Eyes', 18005, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092773, 'Mousse', 'Mousse', 18006, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092775, 'Peryton', 'Peryton', 18028, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092785, 'Mousse', 'Mousse', 18006, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092787, 'Draugar', 'Draugar', 18015, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092797, 'Mousse', 'Mousse', 18006, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092799, 'Mousse', 'Mousse', 18006, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092805, 'Black_Pudding', 'Black Pudding', 18007, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092811, 'Killing_Weapon', 'Killing Weapon', 18008, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092814, 'Ominous_Weapon', 'Ominous Weapon', 18009, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092817, 'Magic_Flagon', 'Magic Flagon', 18010, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092823, 'Dahak', 'Dahak', 18041, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092824, 'Bat_Eye', 'Bat Eye', 18042, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092833, 'Cactuar_Cantautor', 'Cactuar Cantautor', 18051, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092842, 'Old_Two-Wings', 'Old Two-Wings', 18060, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092851, 'Bloodtear_Baldurf', 'Bloodtear Baldurf', 18069, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092860, 'Fungus_Beetle', 'Fungus Beetle', 18078, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092869, 'Roc', 'Roc', 18087, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092878, 'Golden_Bat', 'Golden Bat', 18095, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092887, 'Odqan', 'Odqan', 18104, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092896, 'Panzer_Percival', 'Panzer Percival', 18111, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092905, 'Simurgh', 'Simurgh', 18120, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092913, 'Taisaijin', 'Taisaijin', 18077, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092916, 'Archaic_Gear', 'Archaic Gear', 18127, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092918, 'Archaic_Gear', 'Archaic Gear', 18127, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092919, 'Archaic_Gears', 'Archaic Gears', 18128, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092921, 'Archaic_Gears', 'Archaic Gears', 18128, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092944, 'Mokke', 'Mokke', 18129, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092945, 'Mokka', 'Mokka', 18130, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092946, 'Mokku', 'Mokku', 18131, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092947, 'Vile_Wahdaha', 'Vile Wahdaha', 18132, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092948, 'Vile_Ineef', 'Vile Ineef', 18133, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092949, 'Vile_Yabeewa', 'Vile Yabeewa', 18134, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092950, 'Uriri_Samariri', 'Uriri Samariri', 18135, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092951, 'Eriri_Samariri', 'Eriri Samariri', 18136, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092952, 'Oriri_Samariri', 'Oriri Samariri', 18137, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092953, 'Ginger_Custard', 'Ginger Custard', 18138, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092954, 'Anise_Custard', 'Anise Custard', 18139, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092955, 'Cumin_Custard', 'Cumin Custard', 18140, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092956, 'Nutmeg_Custard', 'Nutmeg Custard', 18141, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092957, 'Mint_Custard', 'Mint Custard', 18142, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092958, 'Cinnamon_Custard', 'Cinnamon Custard', 18143, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092959, 'Caraway_Custard', 'Caraway Custard', 18144, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092960, 'Vanilla_Custard', 'Vanilla Custard', 18145, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092961, 'Gem_Heister_Roorooroon', 'Gem Heister Roorooroon', 18146, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092962, 'Qiqirn_Mine', 'Qiqirn Mine', 18147, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092963, 'Stealth_Bomber_Gagaroon', 'Stealth Bomber Gagaroon', 18148, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092964, 'Quick_Draw_Sasaroon', 'Quick Draw Sasaroon', 18149, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092965, 'Shielded_Chariot', 'Shielded Chariot', 18150, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092966, 'Battledressed_Chariot', 'Battledressed Chariot', 18151, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092967, 'Long-Gunned_Chariot', 'Long-Gunned Chariot', 18152, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092968, 'Long-Horned_Chariot', 'Long-Horned Chariot', 18153, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092969, 'Heraldic_Imp', 'Heraldic Imp', 18154, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092974, 'Psycheflayer', 'Psycheflayer', 18022, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092979, 'Poroggo_Gent', 'Poroggo Gent', 18155, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092984, 'Ebony_Pudding', 'Ebony Pudding', 18156, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092989, 'Qiqirn_Treasure_Hunter', 'Qiqirn Treasure Hunter', 18157, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092991, 'Qiqirn_Archaeologist', 'Qiqirn Archaeologist', 18158, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092994, 'Racing_Chariot', 'Racing Chariot', 18159, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17092998, 'Racing_Chariot', 'Racing Chariot', 18159, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17093000, 'Behemoth', 'Behemoth', 18160, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17093001, 'Fafnir', 'Fafnir', 18161, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17093002, 'Khimaira', 'Khimaira', 18162, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17093003, 'Hydra', 'Hydra', 18163, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17093004, 'Cerberus', 'Cerberus', 18164, 1, 1, 1, 0);
INSERT INTO `mob_spawn_points` (`mobid`, `mobname`, `polutils_name`, `groupid`, `pos_x`, `pos_y`, `pos_z`, `pos_rot`) VALUES (17093102, 'Adamantoise', 'Adamantoise', 18165, 1, 1, 1, 0);
