"""Regenerates NM-DETAILS.md from the live DB (dspdb_fresh) + each NM's mob script.
Run from the repo root: py -3 docs/voidwatch/gen_nm_details.py
Every value here is read, never invented. Evidence tags live in the scripts/SQL comments; the
'Verified' column is filled by hand in NM-DETAILS-NOTES.md (not overwritten by this script)."""
import mysql.connector as m, re, glob, os, json
cf = open('conf/map_darkstar.conf').read()
pw = re.search(r'mysql_password:\s*(\S+)', cf).group(1)
cn = m.connect(host='127.0.0.1', user='root', password=pw, database='dspdb_fresh'); c = cn.cursor()
def q(sql, a=()):
    c.execute(sql, a); return c.fetchall()
trk = {t['name']: t for t in json.load(open('docs/voidwatch/NM-TRACKER.json'))}
out = ["# Voidwatch NM Details (generated)", "",
 "Companion to `NM-TRACKER` (presence / rift locations / gating). This sheet tracks **stats, skills, spells, drops**.",
 "Generated by `gen_nm_details.py` from the live `dspdb_fresh` + mob scripts. `HP 0` = no override (level/job/family formula).",
 "Column `src` for hand-checked values lives in `NM-DETAILS-NOTES.md`. Unknown = `?`, never guessed.", ""]
rows = []
for f in sorted(glob.glob('scripts/zones/*/npcs/Planar_Rift.lua')):
    s = open(f, encoding='utf-8').read(); z = f.replace(chr(92), '/').split('/')[2]
    mf = re.search(r'MOB_FIRST\s*=\s*(\d+)', s)
    if not mf: continue
    mf = int(mf.group(1))
    for i in range(3):
        r = q("select s.mobname,g.groupid,g.minLevel,g.maxLevel,g.HP,g.MP,g.dropid,g.respawntime,p.poolid,p.familyid,p.mJob,p.sJob,p.mobType,p.immunity,p.skill_list_id,p.spellList,p.cmbDelay,p.cmbDmgMult from mob_spawn_points s join mob_groups g on g.groupid=s.groupid join mob_pools p on p.poolid=g.poolid where s.mobid=%s", (mf + i,))
        if r: rows.append((z, mf + i, r[0]))
seen = {}
for z, mid, r in rows:
    seen.setdefault((z, r[0]), []).append((mid, r))
JOBS = {1:'WAR',2:'MNK',3:'WHM',4:'BLM',5:'RDM',6:'THF',7:'PLD',8:'DRK',9:'BST',10:'BRD',11:'RNG',12:'SAM',13:'NIN',14:'DRG',15:'SMN',16:'BLU',17:'COR',18:'PUP',19:'DNC',20:'SCH'}
summary = ["| NM | Zone | Lv | mobType | Job | HP override | Skills | Spells | Drops (script) |", "|---|---|---|---|---|---|---|---|---|"]
detail = []
for (z, name), lst in seen.items():
    mid, r = lst[0]
    (_, gid, lo, hi, hp, mp, dropid, resp, pool, fam, mj, sj, mt, imm, sl, spl, cd, cdm) = r
    fam_r = q("select family,HP,ATT,DEF,ACC,EVA from mob_family_system where familyid=%s", (fam,))
    fam_r = fam_r[0] if fam_r else ('?',) * 6
    skills = [x[0] for x in q("select k.mob_skill_name from mob_skill_lists l join mob_skills k on k.mob_skill_id=l.mob_skill_id where l.skill_list_id=%s", (sl,))] if sl else []
    spells = len(q("select 1 from mob_spell_lists where spell_list_id=%s", (spl,))) if spl else 0
    sf = 'scripts/zones/%s/mobs/%s.lua' % (z, name)
    st = open(sf, encoding='utf-8').read() if os.path.exists(sf) else ''
    drops = [int(x) for x in re.findall(r'drops\s*=\s*\{([\d,\s]+)\}', st)[0].replace(' ', '').split(',') if x] if re.search(r'drops\s*=\s*\{', st) else []
    dn = [(d, (q("select name from item_basic where itemid=%s", (d,)) or [('?',)])[0][0]) for d in drops]
    mods = re.findall(r'^\s*mob:(?:setMod|addMod|setMobMod)\(([^)]*)\)\s*;?\s*(?:--\s*(.*))?$', st, re.M)
    reg = re.search(r'region\s*=\s*"(\w+)"\s*,\s*stage\s*=\s*(\d+)', st)
    ki = re.search(r'keyitem\s*=\s*(\w+)', st)
    t = trk.get(name.replace('_', ' '), trk.get(name, {}))
    jb = '%s/%s' % (JOBS.get(mj, mj), JOBS.get(sj, sj))
    sk = ', '.join(skills) or '—'
    summary.append("| %s | %s | %s-%s | %s | %s | %s | %d skills | %s | %s |" % (name, z, lo, hi, mt, jb, hp if hp else '0 (formula)', len(skills), ('list %s (%d)' % (spl, spl and spells)) if spl else '—', ', '.join(n for _, n in dn) or '—'))
    d = ["### %s — %s" % (name, z), "",
     "| field | value |", "|---|---|",
     "| mob ids | %s |" % ', '.join(str(a) for a, _ in lst),
     "| group / pool / family | %s / %s / %s (%s) |" % (gid, pool, fam, fam_r[0]),
     "| level | %s-%s |" % (lo, hi),
     "| mobType (2 = NM) | %s |" % mt, "| main/sub job | %s |" % jb,
     "| HP override / MP | %s / %s |" % (hp, mp), "| family HP/ATT/DEF/ACC/EVA | %s / %s / %s / %s / %s |" % fam_r[1:],
     "| melee delay / dmg mult | %s / %s |" % (cd, cdm), "| respawn | %s |" % resp,
     "| immunity bitmask | %s |" % imm,
     "| skill list %s | %s |" % (sl, sk),
     "| spell list %s | %s spell rows |" % (spl, spells),
     "| mob_groups.dropid | %s |" % dropid,
     "| Pyxis rare drops (script) | %s |" % (', '.join('%s (%s)' % (n, i) for i, n in dn) or '—'),
     "| reward table | %s |" % ('%s stage %s' % reg.groups() if reg else '?'),
     "| key item drop | %s |" % (ki.group(1) if ki else '—'),
     "| tracker gaps | %s |" % (t.get('gaps', '?') if t else '?'), ""]
    if mods:
        d.append("Script mods:"); d += ["- `%s`%s" % (a.strip(), (' — ' + b) if b else '') for a, b in mods]; d.append("")
    detail.append("\n".join(d))
out += summary + ["", "## Per-NM detail", ""] + detail
open('docs/voidwatch/NM-DETAILS.md', 'w', encoding='utf-8').write("\n".join(out) + "\n")
print(len(seen), 'NMs')

# --- NM-DETAILS-NOTES.md: hand-edited source/verified ledger. Created once, NEVER overwritten. ---
NOTES = 'docs/voidwatch/NM-DETAILS-NOTES.md'
if not os.path.exists(NOTES):
    PREFILL = {  # (NM, field) -> (source, verified, note); only facts established in this project's sessions
        ('Pancimanci', 'level'): ('U', 'user-stated', '83, easy to kill, plain mob (2026-10-07)'),
        ('Pancimanci', 'mobType'): ('U', 'user-stated', 'not an NM'),
        ('Melancholic_Moira', 'HP'): ('D', 'no', 'estimate from capture kill time (~80 s)'),
        ('Melancholic_Moira', 'skills'): ('D', 'no', 'capture showed no mob TP moves; skill rows are design guesses'),
        ('Melancholic_Moira', 'key item'): ('V', 'yes', 'client id 1810 per KI-VERIFICATION.md'),
        ('Melancholic_Moira', 'cruor'): ('C', 'yes', '12300 = 6000 x 205% green (Raguza 2021.03.27)'),
        ('Kholomodumo', 'cruor'): ('C', 'yes', '9660 = 6000 x 161% green (Raguza 2021.03.28)'),
        ('Kholomodumo', 'skills'): ('B/C', 'partial', 'Accursed Armor/Amnesic Blast/Ecliptic Meteor from forum+capture; damage/duration [D]; plain Meteor has no skill row'),
        ('Kholomodumo', 'key item'): ('W/F', 'no', 'client-id check pending'),
        ('Cottus', 'rift positions'): ('C', 'yes', 'match capture'),
    }
    FIELDS = ['level', 'mobType', 'main/sub job', 'HP', 'skills', 'spells', 'Pyxis drops', 'key item', 'cruor/EXP', 'mods']
    L = ["# Voidwatch NM Details — Notes (hand-edited)", "",
         "Source and verification ledger for `NM-DETAILS.md`. **This file is never overwritten by the generator.**", "",
         "Source tags: [C] capture, [V] client dat, [J] wikiwiki.jp, [F] FFXIclopedia, [W] BG Wiki, [B] BG forum, [D] design guess, [U] user-stated, `?` = none known.",
         "Verified: `yes` (checked against a ground-truth source), `partial`, `no` (unchecked/guess), `user-stated`.",
         "Values are a snapshot when this file was created; the live numbers are in `NM-DETAILS.md`.", ""]
    for (z, name), lst in seen.items():
        r = lst[0][1]
        L += ["## %s (%s)" % (name, z), "", "| field | value (snapshot) | source | verified | note |", "|---|---|---|---|---|"]
        snap = {'level': '%s-%s' % (r[2], r[3]), 'mobType': r[12], 'main/sub job': '%s/%s' % (JOBS.get(r[10], r[10]), JOBS.get(r[11], r[11])),
                'HP': r[4] if r[4] else '0 (formula)', 'skills': 'list %s' % r[14], 'spells': 'list %s' % r[15], 'Pyxis drops': 'see NM-DETAILS', 'key item': 'see NM-DETAILS', 'cruor/EXP': 'see NM-DETAILS', 'mods': 'see NM-DETAILS'}
        for fld in FIELDS:
            s, v, n = PREFILL.get((name, fld), ('?', 'no', ''))
            L.append("| %s | %s | %s | %s | %s |" % (fld, snap[fld], s, v, n))
        extra = [k for k in PREFILL if k[0] == name and k[1] not in FIELDS]
        for k in extra:
            s, v, n = PREFILL[k]; L.append("| %s | — | %s | %s | %s |" % (k[1], s, v, n))
        L.append("")
    open(NOTES, 'w', encoding='utf-8').write("\n".join(L))
    print('created', NOTES)
