-----------------------------------------
-- ID: 16581
-- Item: Holy Sword
-- Additional Effect: Light Damage
-- GENERATED by the Mission Toolkit from LandSandBoat item_mods {type=1, damage=10, chance=5, element=7}.
-- Draft: values are LSB's and unverified on this server. Review before relying on it.
-----------------------------------------
require("scripts/globals/status");
require("scripts/globals/magic");
require("scripts/globals/msg");

-----------------------------------
-- onAdditionalEffect Action
-----------------------------------

function onAdditionalEffect(player,target,damage)
    local chance = 5;

    if (math.random(0,99) >= chance) then
        return 0,0,0;
    else
        local dmg = 10;
        local params = {};
        params.bonusmab = 0;
        params.includemab = false;
        dmg = addBonusesAbility(player, ELE_LIGHT, target, dmg, params);
        dmg = dmg * applyResistanceAddEffect(player,target,ELE_LIGHT,0);
        dmg = adjustForTarget(target,dmg,ELE_LIGHT);
        dmg = finalMagicNonSpellAdjustments(player,target,ELE_LIGHT,dmg);

        local message = msgBasic.ADD_EFFECT_DMG;
        if (dmg < 0) then
            message = msgBasic.ADD_EFFECT_HEAL;
        end

        return SUBEFFECT_LIGHT_DAMAGE,message,dmg;
    end
end;
