-- Voidwatch framework NMs: pool/group/spawn rows for NMs missing from the live DSP DB. GENERATED by docs/voidwatch/research/gen_framework_nms.py from LSB reference data.
-- Spawn i = Planar Rift i (mobid order). vwSpawnAtRift setPos's the NM onto the rift, so these LSB coordinates are placeholders (must only be non-zero).
-- NOT RUN. Review, then apply via py -3 dbtool.py / direct MariaDB, then restart the map server.
-- New groups use ids >= 18300 (above live max); pools keep their LSB poolid; familyid copied from a DSP pool with the same modelid (0 = none found);
-- skill_list_id/spellList left 0 (DSP-specific ids need mapping). Groups: spawntype 128 (script spawn), HP 0 (formula) until an hptrack value exists.

-- Isarukitsck (zone 5): pool 6811 added
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6811,'Isarukitsck','Isarukitsck',27,0x0000170800000000000000000000000000000000,2,4,1,380,100,0,1,1,1,2,0,32,0,1175,0,0,0,0,0,0);

-- Fjalar (zone 7): pool 6814 added
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6814,'Fjalar','Fjalar',316,0x0000160800000000000000000000000000000000,4,4,12,240,100,0,1,1,0,2,0,32,0,159,0,0,0,0,0,0);

-- Tsui-Goab (zone 25): pool 6739 added (familyid unknown)
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6739,'Tsui-Goab','Tsui-Goab',0,0x00002F0800000000000000000000000000000000,1,1,8,240,100,0,1,1,0,2,0,32,0,671,0,0,0,0,0,0);

-- Dimgruzub (zone 54): 
REPLACE INTO `mob_spawn_points` VALUES (16998881,'Dimgruzub','Dimgruzub',13837,387.494,-2.677,275.046,33);

-- Vanasarvik (zone 61): 
REPLACE INTO `mob_spawn_points` VALUES (17027491,'Vanasarvik','Vanasarvik',13830,463.477,-16.256,-62.603,245);
REPLACE INTO `mob_spawn_points` VALUES (17027496,'Vanasarvik','Vanasarvik',13830,775.982,-16.272,-63.583,234);

-- Yalungur (zone 65): pool 6755 added (familyid unknown); group 18300 added
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6755,'Yalungur','Yalungur',0,0x0000B90600000000000000000000000000000000,5,5,2,220,100,0,0,0,0,0,0,32,0,159,4,0,0,0,0,0);
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18300,6755,65,0,128,0,0,0,99,99,0);
REPLACE INTO `mob_spawn_points` VALUES (17043893,'Yalungur','Yalungur',18300,322.559,-3.598,-186.538,206);
REPLACE INTO `mob_spawn_points` VALUES (17043899,'Yalungur','Yalungur',18300,182.634,13.860,-194.985,8);
REPLACE INTO `mob_spawn_points` VALUES (17043905,'Yalungur','Yalungur',18300,61.315,-4.382,-85.856,19);

-- Morta (zone 68): 
REPLACE INTO `mob_spawn_points` VALUES (17056194,'Morta','Morta',13651,-153.000,8.212,44.000,0);

-- Brekekekex (zone 79): group 18301 added; fresh id block 17101352-17101354 (LSB ids taken or fewer rows than rifts); script base id must follow
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18301,5207,79,0,128,0,0,0,95,96,0);
REPLACE INTO `mob_spawn_points` VALUES (17101352,'Brekekekex','Brekekekex',18301,242.949,-4.942,-491.421,66);
REPLACE INTO `mob_spawn_points` VALUES (17101353,'Brekekekex','Brekekekex',18301,254.210,-2.500,-725.390,152);
REPLACE INTO `mob_spawn_points` VALUES (17101354,'Brekekekex','Brekekekex',18301,-314.613,-4.758,-748.020,117);

-- Gaunab (zone 83): 
REPLACE INTO `mob_spawn_points` VALUES (17117891,'Gaunab','Gaunab',13814,0.000,0.000,0.000,0);
REPLACE INTO `mob_spawn_points` VALUES (17117892,'Gaunab','Gaunab',13814,-154.184,-32.672,118.197,206);

-- Taweret (zone 84): 
REPLACE INTO `mob_spawn_points` VALUES (17122050,'Taweret','Taweret',13824,270.294,8.100,-391.839,212);
REPLACE INTO `mob_spawn_points` VALUES (17122051,'Taweret','Taweret',13824,-320.000,-16.500,-42.000,226);

-- Cetus (zone 89): pool 6821 added (familyid unknown); group 18302 added; fresh id block 17142639-17142641 (LSB ids taken or fewer rows than rifts); script base id must follow; LSB spawns 1 vs DB rifts 3
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6821,'Cetus','Cetus',0,0x0000710B00000000000000000000000000000000,1,1,2,240,100,0,1,0,1,2,0,32,0,129,0,0,0,0,0,0);
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18302,6821,89,0,128,0,0,0,150,150,0);
REPLACE INTO `mob_spawn_points` VALUES (17142639,'Cetus','Cetus',18302,-123.725,-7.284,590.606,59);
REPLACE INTO `mob_spawn_points` VALUES (17142640,'Cetus','Cetus',18302,-80.0,-7.32,-385.0,0);
REPLACE INTO `mob_spawn_points` VALUES (17142641,'Cetus','Cetus',18302,72.0,-47.691,285.0,0);

-- Ocythoe (zone 89): 
REPLACE INTO `mob_spawn_points` VALUES (17142450,'Ocythoe','Ocythoe',13724,-80.000,-7.799,-385.000,0);
REPLACE INTO `mob_spawn_points` VALUES (17142451,'Ocythoe','Ocythoe',13724,72.000,-48.187,285.000,7);

-- Agathos (zone 91): 
REPLACE INTO `mob_spawn_points` VALUES (17150670,'Agathos','Agathos',13757,-435.008,-8.318,14.300,64);
REPLACE INTO `mob_spawn_points` VALUES (17150671,'Agathos','Agathos',13757,-633.295,-24.268,-269.822,130);

-- Gugalanna (zone 98): 
REPLACE INTO `mob_spawn_points` VALUES (17179263,'Gugalanna','Gugalanna',13780,-245.000,7.425,245.000,4);
REPLACE INTO `mob_spawn_points` VALUES (17179264,'Gugalanna','Gugalanna',13780,80.000,31.500,323.000,186);

-- Cherufe (zone 105): 
REPLACE INTO `mob_spawn_points` VALUES (17207725,'Cherufe','Cherufe',13825,-320.000,-16.500,-42.000,0);

-- Bhishani (zone 107): group 18303 added; fresh id block 17216233-17216235 (LSB ids taken or fewer rows than rifts); script base id must follow
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18303,4688,107,0,128,0,0,0,99,99,0);
REPLACE INTO `mob_spawn_points` VALUES (17216233,'Bhishani','Bhishani',18303,605.000,-0.964,-520.000,198);
REPLACE INTO `mob_spawn_points` VALUES (17216234,'Bhishani','Bhishani',18303,615.652,-3.213,-519.283,112);
REPLACE INTO `mob_spawn_points` VALUES (17216235,'Bhishani','Bhishani',18303,0.000,0.000,0.000,0);

-- Gwynn Ap Nudd (zone 108): 
REPLACE INTO `mob_spawn_points` VALUES (17220020,'Gwynn_ap_Nudd','Gwynn ap Nudd',13804,-125.000,71.549,720.000,231);
REPLACE INTO `mob_spawn_points` VALUES (17220022,'Gwynn_ap_Nudd','Gwynn ap Nudd',13804,200.000,-24.500,-400.000,50);

-- Yatagarasu (zone 110): 
REPLACE INTO `mob_spawn_points` VALUES (17228263,'Yatagarasu','Yatagarasu',13755,-435.000,-8.406,15.000,212);
REPLACE INTO `mob_spawn_points` VALUES (17228264,'Yatagarasu','Yatagarasu',13755,-630.000,-24.266,-270.000,19);

-- Rw Nw Prt M Hrw (zone 116): 
REPLACE INTO `mob_spawn_points` VALUES (17252817,'Rw_Nw_Prt_M_Hrw','Rw Nw Prt M Hrw',13749,0.000,0.000,0.000,0);
REPLACE INTO `mob_spawn_points` VALUES (17252818,'Rw_Nw_Prt_M_Hrw','Rw Nw Prt M Hrw',13749,0.000,0.000,0.000,0);

-- Goji (zone 120): 
REPLACE INTO `mob_spawn_points` VALUES (17269128,'Goji','Goji',13779,0.000,0.000,0.000,0);
REPLACE INTO `mob_spawn_points` VALUES (17269129,'Goji','Goji',13779,490.825,7.841,-281.568,157);

-- Cath Palug (zone 121): 
REPLACE INTO `mob_spawn_points` VALUES (17273315,'Cath_Palug','Cath Palug',13732,-273.766,-0.139,46.751,114);
REPLACE INTO `mob_spawn_points` VALUES (17273321,'Cath_Palug','Cath Palug',13732,-399.274,0.012,-133.128,80);

-- Holy Moly (zone 123): pool 6847 added (familyid unknown); group 18304 added
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6847,'Holy_Moly','Holy_Moly',0,0x0000EA0700000000000000000000000000000000,1,1,7,240,100,0,1,0,1,2,0,32,0,647,0,0,0,0,0,0);
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18304,6847,123,0,128,0,0,0,0,0,0);
REPLACE INTO `mob_spawn_points` VALUES (17281497,'Holy_Moly','Holy Moly',18304,-241.825,-0.500,405.212,54);
REPLACE INTO `mob_spawn_points` VALUES (17281500,'Holy_Moly','Holy Moly',18304,0.000,0.000,0.000,0);
REPLACE INTO `mob_spawn_points` VALUES (17281503,'Holy_Moly','Holy Moly',18304,-337.240,17.298,-366.860,30);

-- Sabotender Campeador (zone 125): pool 6851 added (familyid unknown); group 18305 added
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6851,'Sabotender_Campeador','Sabotender_Campeador',0,0x0000760100000000000000000000000000000000,12,12,7,240,100,0,1,1,0,2,0,0,0,135,0,0,0,0,0,0);
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18305,6851,125,0,128,0,0,0,0,0,0);
REPLACE INTO `mob_spawn_points` VALUES (17289658,'Sabotender_Campeador','Sabotender Campeador',18305,551.088,-0.068,257.063,73);
REPLACE INTO `mob_spawn_points` VALUES (17289664,'Sabotender_Campeador','Sabotender Campeador',18305,0.000,0.000,0.000,0);
REPLACE INTO `mob_spawn_points` VALUES (17289670,'Sabotender_Campeador','Sabotender Campeador',18305,0.000,0.000,0.000,0);

-- Neith (zone 159): pool 6726 added; group 18306 added
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6726,'Neith','Neith',81,0x00004A0500000000000000000000000000000000,12,12,10,240,100,0,1,0,0,2,0,32,0,671,8,0,0,0,0,0);
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18306,6726,159,0,128,0,0,0,0,0,0);
REPLACE INTO `mob_spawn_points` VALUES (17428818,'Neith','Neith',18306,179.723,0.000,-61.927,249);
REPLACE INTO `mob_spawn_points` VALUES (17428824,'Neith','Neith',18306,259.972,0.000,60.831,22);
REPLACE INTO `mob_spawn_points` VALUES (17428830,'Neith','Neith',18306,-143.783,0.985,-23.117,37);

-- Laidly Laurence (zone 164): group 18307 added; fresh id block 17449569-17449571 (LSB ids taken or fewer rows than rifts); script base id must follow
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18307,5146,164,0,128,0,0,0,91,93,0);
REPLACE INTO `mob_spawn_points` VALUES (17449569,'Laidly_Laurence','Laidly Laurence',18307,-260.000,-0.580,-20.000,223);
REPLACE INTO `mob_spawn_points` VALUES (17449570,'Laidly_Laurence','Laidly Laurence',18307,-190.068,-0.579,139.325,9);
REPLACE INTO `mob_spawn_points` VALUES (17449571,'Laidly_Laurence','Laidly Laurence',18307,-59.667,-0.500,-61.870,10);

-- Nympha Eunomia (zone 171): 
REPLACE INTO `mob_spawn_points` VALUES (17478059,'Nympha_Eunomia','Nympha Eunomia',13759,-187.910,-0.673,200.811,207);
REPLACE INTO `mob_spawn_points` VALUES (17478061,'Nympha_Eunomia','Nympha Eunomia',13759,-137.000,-0.743,377.000,145);

-- Giltine (zone 175): 
REPLACE INTO `mob_spawn_points` VALUES (17494611,'Giltine','Giltine',13818,42.000,-15.500,322.000,154);

-- Uptala (zone 177): 
REPLACE INTO `mob_spawn_points` VALUES (17502574,'Uptala','Uptala',13739,379.855,0.075,39.644,115);
REPLACE INTO `mob_spawn_points` VALUES (17502577,'Uptala','Uptala',13739,-341.140,0.023,284.829,65);

-- Qilin (zone 178): 
REPLACE INTO `mob_spawn_points` VALUES (17506686,'Qilin','Qilin',13746,-68.000,-15.924,-68.000,185);

-- Akvan (zone 184): 
REPLACE INTO `mob_spawn_points` VALUES (17531128,'Akvan','Akvan',13803,505.000,-32.506,95.000,0);

-- Voidwrought (zone 194): pool 6724 added
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6724,'Voidwrought','Voidwrought',350,0x0000580800000000000000000000000000000000,4,5,4,240,100,0,1,1,0,2,0,0,1,135,0,0,0,0,0,0);

-- Mellonia (zone 197): 
REPLACE INTO `mob_spawn_points` VALUES (17584429,'Mellonia','Mellonia',13754,0.000,0.000,0.000,0);
REPLACE INTO `mob_spawn_points` VALUES (17584430,'Mellonia','Mellonia',13754,0.000,0.000,0.000,0);

-- Roly-Poly (zone 200): 
REPLACE INTO `mob_spawn_points` VALUES (17596730,'Roly-Poly','Roly-Poly',13777,-340.000,-0.500,220.000,107);
REPLACE INTO `mob_spawn_points` VALUES (17596731,'Roly-Poly','Roly-Poly',13777,-261.541,-0.500,379.626,137);

-- Malleator Maurok (zone 208): pool 6900 added (familyid unknown); group 18308 added
REPLACE INTO `mob_pools` (`poolid`,`name`,`packet_name`,`familyid`,`modelid`,`mJob`,`sJob`,`cmbSkill`,`cmbDelay`,`cmbDmgMult`,`behavior`,`aggro`,`true_detection`,`links`,`mobType`,`immunity`,`name_prefix`,`flag`,`entityFlags`,`animationsub`,`hasSpellScript`,`spellList`,`namevis`,`roamflag`,`skill_list_id`) VALUES (6900,'Malleator_Maurok','Malleator_Maurok',0,0x00003B0800000000000000000000000000000000,1,1,5,240,100,0,1,0,1,2,0,32,0,159,0,0,0,0,0,0);
REPLACE INTO `mob_groups` (`groupid`,`poolid`,`zoneid`,`respawntime`,`spawntype`,`dropid`,`HP`,`MP`,`minLevel`,`maxLevel`,`allegiance`) VALUES (18308,6900,208,0,128,0,0,0,99,99,0);
REPLACE INTO `mob_spawn_points` VALUES (17629646,'Malleator_Maurok','Malleator Maurok',18308,-83.623,-0.031,-39.748,69);
REPLACE INTO `mob_spawn_points` VALUES (17629649,'Malleator_Maurok','Malleator Maurok',18308,0.000,0.000,0.000,0);
REPLACE INTO `mob_spawn_points` VALUES (17629652,'Malleator_Maurok','Malleator Maurok',18308,41.024,-0.500,-130.467,45);
